<?xml version="1.0"?>
<package>
  <name>sm_matrix_archive</name>
  <version>0.0.1</version>
  <description>sm_matrix_archive</description>

  <maintainer email="paul.furgale@mavt.ethz.ch">Paul Furgale</maintainer>
  <license>New BSD</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>eigen</build_depend>
  <build_depend>sm_common</build_depend>
  <run_depend>sm_common</run_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
