<?xml version="1.0" encoding="utf-8"?>
<package format="3">
  <name>incremental_calibration_python</name>
  <version>0.0.1</version>
  <description>
    A C++-based library for providing python interface to the incremental
    calibration package.
  </description>
  <maintainer email="jerome.maye@mavt.ethz.ch">Jerome Maye</maintainer>
  <license>LGPLv3</license>
  <url type="website">https://github.com/ethz-asl/aslam_incremental_calibration</url>
  <author email="jerome.maye@mavt.ethz.ch">Jerome Maye</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <build_depend>incremental_calibration</build_depend>
  <build_depend>numpy_eigen</build_depend>
  <build_depend>aslam_backend</build_depend>
  <exec_depend>incremental_calibration</exec_depend>
  <exec_depend>numpy_eigen</exec_depend>
  <exec_depend>aslam_backend</exec_depend>
  <exec_depend>aslam_backend_python</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
